import express from "express";
import cors from "cors";
import crypto from "node:crypto";
import { CommerceError, DEMO_PROJECT_ID, SKILL_CATALOG, getCommerceService } from "@lai/shared";
import type { AgentPrincipal } from "@lai/permissions";

const service=getCommerceService();
const base=process.env.A2A_URL||"http://127.0.0.1:3102";
export const agentCard={
  name:"LaiCommerce Studio Agent",description:"在获授权项目内读取事实与资料，生成电商方案、脚本、视觉规划和智能体交接草稿，并把高风险内容送交人类审核。",
  supportedInterfaces:[{url:`${base}/a2a/rpc`,protocolBinding:"JSONRPC",protocolVersion:"1.0"},{url:`${base}/a2a/v1`,protocolBinding:"HTTP+JSON",protocolVersion:"1.0"}],
  provider:{organization:"LaiCommerce Studio",url:process.env.WEB_URL||"http://127.0.0.1:3000"},version:"0.1.0",documentationUrl:`${process.env.WEB_URL||"http://127.0.0.1:3000"}/api-docs`,
  capabilities:{streaming:true,pushNotifications:true,extendedAgentCard:false},
  securitySchemes:{bearer:{httpAuthSecurityScheme:{scheme:"Bearer",bearerFormat:"opaque agent token",description:"由小赖电商工作台创建、可撤销并可限制项目的智能体 Token"}}},
  securityRequirements:[{schemes:{bearer:{list:[]}}}],defaultInputModes:["application/json","text/plain"],defaultOutputModes:["application/json","text/markdown"],
  skills:SKILL_CATALOG.map(skill=>({id:skill.name,name:skill.description,description:`${skill.description}。所有事实型内容使用同一 Fact Snapshot；写入只进入草稿区。`,tags:["ecommerce","source-grounded",skill.name],examples:[skill.name==="ecommerce-script-writer"?"为获准商品写一条30秒短视频脚本":"为获准项目继续完成电商内容"],inputModes:["application/json","text/plain"],outputModes:["application/json","text/markdown"]}))
};

type A2ATask={id:string;contextId:string;status:{state:string;message?:any;timestamp:string};artifacts?:any[];history?:any[];metadata?:Record<string,unknown>};
const textPart=(text:string)=>({text,mediaType:"text/plain"});
const message=(role:"ROLE_USER"|"ROLE_AGENT",text:string,taskId?:string,contextId?:string)=>({messageId:crypto.randomUUID(),role,parts:[textPart(text)],taskId,contextId});

function version(req:express.Request,res:express.Response){const value=req.header("A2A-Version")||String(req.query["A2A-Version"]||"");if(value!=="1.0"){res.status(400).json({error:{code:"VersionNotSupportedError",message:"本服务支持 A2A 1.0；请发送 A2A-Version: 1.0"}});return false;}return true;}
function principal(req:express.Request):AgentPrincipal{const auth=req.header("authorization");if(!auth?.startsWith("Bearer "))throw new CommerceError("UNAUTHORIZED","请提供 Bearer 智能体 Token",401);return service.authenticate(auth.slice(7));}
function objectiveFrom(params:any){const parts=params?.message?.parts||[];const text=parts.map((part:any)=>typeof part?.text==="string"?part.text:typeof part?.text?.text==="string"?part.text.text:"").filter(Boolean).join("\n");return text||String(params?.metadata?.objective||"为获准项目生成电商方案");}
async function sendMessage(params:any,actor:AgentPrincipal):Promise<A2ATask>{const projectId=String(params?.metadata?.projectId||params?.message?.metadata?.projectId||DEMO_PROJECT_ID);service.assert(actor,"project:read",projectId);service.assert(actor,"prompt:write",projectId);const objective=objectiveFrom(params);const prompt=service.generatePrompt(projectId,objective);service.assert(actor,"artifact:write",projectId);const output=await service.runPrompt(projectId,prompt.spec.id,objective.includes("脚本")?"script":"proposal");const version=output.artifact.version;const task:A2ATask={id:crypto.randomUUID(),contextId:params?.message?.contextId||crypto.randomUUID(),status:{state:"TASK_STATE_COMPLETED",message:message("ROLE_AGENT","已生成草稿。涉及价格、规格、资质、功效或发布时仍需人类审核。"),timestamp:new Date().toISOString()},artifacts:[{artifactId:output.artifact.id,name:output.artifact.title,description:"LaiCommerce 草稿成果",parts:[textPart(version.content)],metadata:{projectId,factSnapshotId:output.artifact.factSnapshotId,status:"draft",humanReviewRequired:true}}],history:[params.message],metadata:{projectId,promptSpecId:prompt.spec.id,permissionScope:actor.scopes}};service.repo.save("skill_runs",{...task,workspaceId:actor.workspaceId,projectId,updatedAt:new Date().toISOString()},{workspaceId:actor.workspaceId,projectId,status:"completed"});return task;}
function getTask(id:string,actor:AgentPrincipal){const task=service.repo.get<A2ATask>("skill_runs",id,actor.workspaceId);if(!task)throw new CommerceError("TaskNotFoundError","没有找到这个 A2A 任务",404);const projectId=String(task.metadata?.projectId||DEMO_PROJECT_ID);service.assert(actor,"job:read",projectId);return task;}

const app=express();app.disable("x-powered-by");app.use(cors({origin:false}));app.use(express.json({limit:"2mb"}));
app.get("/health",(_,res)=>res.json({status:"ok",protocol:"A2A 1.0"}));
app.get("/.well-known/agent-card.json",(req,res)=>{const etag='"lai-agent-0.1.0"';if(req.header("if-none-match")===etag)return res.status(304).end();res.set({"cache-control":"public, max-age=300","etag":etag}).json(agentCard)});

app.post("/a2a/rpc",async(req,res)=>{if(!version(req,res))return;const id=req.body?.id??null;try{const actor=principal(req);const method=req.body?.method;let result:unknown;if(method==="SendMessage")result=await sendMessage(req.body.params,actor);else if(method==="GetTask")result=getTask(String(req.body.params?.id),actor);else if(method==="CancelTask"){const task=getTask(String(req.body.params?.id),actor);task.status={state:"TASK_STATE_CANCELED",timestamp:new Date().toISOString()};service.repo.save("skill_runs",{...task,workspaceId:actor.workspaceId,projectId:String(task.metadata?.projectId),updatedAt:new Date().toISOString()},{workspaceId:actor.workspaceId,projectId:String(task.metadata?.projectId),status:"canceled"});result=task;}else throw new CommerceError("MethodNotFound",`不支持 A2A 方法：${method}`,404);res.json({jsonrpc:"2.0",id,result});}catch(error){const status=error instanceof CommerceError?error.status:500;res.status(status).json({jsonrpc:"2.0",id,error:{code:error instanceof CommerceError?-32001:-32603,message:error instanceof Error?error.message:"A2A request failed",data:{type:error instanceof CommerceError?error.code:"InternalError"}}});}});

app.post("/a2a/stream",async(req,res)=>{if(!version(req,res))return;try{const actor=principal(req);res.set({"content-type":"text/event-stream","cache-control":"no-cache","connection":"keep-alive"});const contextId=req.body?.params?.message?.contextId||crypto.randomUUID();const tempId=crypto.randomUUID();res.write(`event: status\ndata: ${JSON.stringify({statusUpdate:{taskId:tempId,contextId,status:{state:"TASK_STATE_WORKING",timestamp:new Date().toISOString()}}})}\n\n`);const task=await sendMessage(req.body.params,actor);res.write(`event: artifact\ndata: ${JSON.stringify({artifactUpdate:{taskId:task.id,contextId:task.contextId,artifact:task.artifacts?.[0],lastChunk:true}})}\n\n`);res.write(`event: status\ndata: ${JSON.stringify({statusUpdate:{taskId:task.id,contextId:task.contextId,status:task.status}})}\n\n`);res.end();}catch(error){res.write(`event: error\ndata: ${JSON.stringify({error:{message:error instanceof Error?error.message:"A2A stream failed"}})}\n\n`);res.end();}});

app.post("/a2a/v1/messages:send",async(req,res)=>{if(!version(req,res))return;try{const actor=principal(req);const idempotencyKey=req.header("idempotency-key");const cacheKey=idempotencyKey?`a2a:${actor.id}:${idempotencyKey}`:undefined;const previous=cacheKey?service.repo.getIdempotency<A2ATask>(cacheKey):undefined;if(previous)return res.json(previous);const task=await sendMessage(req.body,actor);if(cacheKey)service.repo.rememberIdempotency(cacheKey,task);res.json(task);}catch(error){res.status(error instanceof CommerceError?error.status:500).json({error:{code:error instanceof CommerceError?error.code:"A2A_ERROR",message:error instanceof Error?error.message:"A2A request failed"}})}});
app.get("/a2a/v1/tasks/:id",(req,res)=>{if(!version(req,res))return;try{res.json(getTask(req.params.id,principal(req)));}catch(error){res.status(error instanceof CommerceError?error.status:500).json({error:{code:error instanceof CommerceError?error.code:"A2A_ERROR",message:error instanceof Error?error.message:"A2A request failed"}})}});
app.post(/^\/a2a\/v1\/tasks\/([^/]+):cancel$/,(req,res)=>{if(!version(req,res))return;try{const actor=principal(req);const task=getTask(String(req.params[0]),actor);task.status={state:"TASK_STATE_CANCELED",timestamp:new Date().toISOString()};const projectId=String(task.metadata?.projectId||DEMO_PROJECT_ID);service.repo.save("skill_runs",{...task,workspaceId:actor.workspaceId,projectId,updatedAt:new Date().toISOString()},{workspaceId:actor.workspaceId,projectId,status:"canceled"});res.json(task);}catch(error){res.status(error instanceof CommerceError?error.status:500).json({error:{code:error instanceof CommerceError?error.code:"A2A_ERROR",message:error instanceof Error?error.message:"A2A request failed"}})}});

const port=Number(process.env.A2A_PORT||3102);app.listen(port,"127.0.0.1",()=>console.log(`LaiCommerce A2A listening on http://127.0.0.1:${port}`));
export {app,sendMessage};
