"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, LoaderCircle, UploadCloud } from "lucide-react";
import { useRouter } from "next/navigation";

const steps = ["选择任务","品牌与商品","上传资料","设置目标","AI 预检查"];
const templates: Array<[string, string]> = [["新品上市","从资料到整套上市内容"],["大型促销","活动机制与内容矩阵"],["日常营销","持续内容与转化实验"],["直播活动","货盘、节奏与直播脚本"],["短视频投放","开场 A/B 与素材规划"],["商品详情页重做","卖点、证据与页面结构"],["品牌年度规划","目标、节奏与预算"],["渠道增长","流量、转化与复购"],["竞品研究","证据化竞品对比"]];

export function ProjectWizard() {
  const [step,setStep] = useState(0); const [type,setType] = useState("新品上市"); const [name,setName] = useState("青麦脆中秋上新计划"); const [platforms,setPlatforms] = useState(["小红书","抖音"]); const [objective,setObjective] = useState("用一套有事实依据的内容验证新品首购转化"); const [loading,setLoading] = useState(false); const router=useRouter();
  async function create(){setLoading(true);const response=await fetch("/api/v1/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,type,brandId:"brand_wuqinggu",productIds:["product_qingmaicui"],objective,targetPlatforms:platforms})});const json=await response.json();setLoading(false);if(response.ok)router.push(`/projects/${json.data.id}`);}
  return <div className="wizard"><aside className="card wizard-steps">{steps.map((label,index)=><div className={`wizard-step ${step===index?"active":""}`} key={label}><span className="wizard-number">{index<step?<CheckCircle2 size={13}/>:index+1}</span><span>{label}</span></div>)}</aside><section className="card wizard-body">
    {step===0&&<><h2>这次要完成哪类任务？</h2><p className="subtitle">先选业务任务，系统会自动准备对应的事实项、提示词和工作室。</p><div className="choice-grid" style={{marginTop:22}}>{templates.map(([label,desc])=><button className={`choice ${type===label?"selected":""}`} onClick={()=>setType(label)} key={label}><strong>{label}</strong><small>{desc}</small></button>)}</div></>}
    {step===1&&<><h2>选择品牌和商品</h2><p className="subtitle">演示环境已准备一个完全虚构的品牌与商品。</p><div className="grid-2" style={{marginTop:22}}><div className="choice selected"><strong>雾青谷</strong><small>清楚、克制、有生活感 · 虚构品牌</small></div><div className="choice selected"><strong>青麦脆·草莓燕麦杯</strong><small>45克×6杯 · 已确认商品资料</small></div></div><div className="field" style={{marginTop:20}}><label>项目名称</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div></>}
    {step===2&&<><h2>上传资料</h2><p className="subtitle">可稍后在项目中上传。这里先使用虚构商品资料单完成演示。</p><div className="card" style={{marginTop:22,padding:38,textAlign:"center",borderStyle:"dashed"}}><UploadCloud size={30} style={{color:"var(--indigo)",margin:"0 auto 12px"}}/><strong style={{fontSize:13}}>拖拽 PDF、Office、表格、文本或图片</strong><p className="hint" style={{margin:"8px 0 0"}}>单文件不超过 20MB；文件会隔离保存并经过类型与路径检查</p></div><div className="list-item"><CheckCircle2 size={18} color="var(--jade)"/><div className="list-copy"><div className="list-title">虚构商品资料单-v1.md</div><div className="list-meta">已解析 · 4 条有来源事实</div></div></div></>}
    {step===3&&<><h2>设置目标</h2><p className="subtitle">只展示运营人员认识的字段，高级模型设置保持折叠。</p><div className="stack" style={{marginTop:22}}><div className="field"><label>业务目标</label><textarea className="textarea" value={objective} onChange={e=>setObjective(e.target.value)}/></div><div className="field"><label>目标平台</label><div className="row">{["小红书","抖音","淘宝","京东"].map(item=><button className={`choice ${platforms.includes(item)?"selected":""}`} style={{padding:"10px 14px"}} onClick={()=>setPlatforms(current=>current.includes(item)?current.filter(p=>p!==item):[...current,item])} key={item}><strong>{item}</strong></button>)}</div></div><div className="grid-2"><div className="field"><label>预算</label><input className="input" type="number" defaultValue="30000"/></div><div className="field"><label>活动时间</label><input className="input" type="date" defaultValue="2026-09-10"/></div></div></div></>}
    {step===4&&<><h2>AI 预检查</h2><p className="subtitle">创建后仍可修改；系统不会把推荐值当成已确认事实。</p><div className="grid-3" style={{marginTop:22}}><div className="card card-pad"><div className="metric-label">已识别事实</div><div className="metric-value" style={{color:"var(--jade)"}}>4</div><div className="metric-note">商品名、规格、配料、产地</div></div><div className="card card-pad"><div className="metric-label">必须确认</div><div className="metric-value" style={{color:"var(--amber)"}}>1</div><div className="metric-note">活动价仍缺失</div></div><div className="card card-pad"><div className="metric-label">推荐技能</div><div className="metric-value">6</div><div className="metric-note">方案、脚本、视觉与复核</div></div></div><div className="card card-pad" style={{marginTop:16,background:"var(--amber-soft)"}}><strong style={{fontSize:12}}>创建后先确认活动价</strong><p className="hint" style={{margin:"6px 0 0"}}>在确认前，系统会用“待确认”占位，不把价格写进可发布内容。</p></div></>}
    <div className="row between" style={{marginTop:30}}><button className="button secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={15}/>上一步</button>{step<4?<button className="button primary" onClick={()=>setStep(s=>s+1)}>下一步<ArrowRight size={15}/></button>:<button className="button jade" onClick={create} disabled={loading}>{loading?<LoaderCircle size={15}/>:<CheckCircle2 size={15}/>}创建并进入项目</button>}</div>
  </section></div>;
}
