"use client";
import { useMemo, useState, type ChangeEvent } from "react";
import { Check, ChevronRight, FileText, LoaderCircle, Play, RotateCcw, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";
import { Badge, statusLabel, statusTone } from "./ui";

export function ProjectWorkspace({ initial }: { initial: any }) {
  const [data,setData]=useState(initial); const [selected,setSelected]=useState<any>(initial.artifacts?.[0]); const [loading,setLoading]=useState(""); const [toast,setToast]=useState("");
  const snapshot=data.snapshots?.find((item:any)=>item.id===data.project.currentFactSnapshotId)||data.snapshots?.[0];
  async function refresh(){const response=await fetch(`/api/v1/projects/${initial.project.id}`);const json=await response.json();if(response.ok){setData(json.data);setSelected((current:any)=>json.data.artifacts.find((item:any)=>item.id===current?.id)||json.data.artifacts[0]);}}
  async function confirm(fact:any){setLoading(fact.id);const value=fact.value||window.prompt(`请填写${fact.type}`)||"";if(!value){setLoading("");return;}const response=await fetch(`/api/v1/projects/${initial.project.id}/facts/${fact.id}/confirm`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({value})});setLoading("");if(response.ok){setToast(`${fact.type}已确认，并建立新事实快照`);await refresh();}}
  async function bundle(){setLoading("bundle");const response=await fetch("/api/v1/campaigns",{method:"POST",headers:{"content-type":"application/json","idempotency-key":`project-${Date.now()}`},body:JSON.stringify({projectId:initial.project.id})});setLoading("");if(response.ok){setToast("整套活动已生成；高风险字段已进入人工审核边界");await refresh();}}
  async function review(){if(!selected)return;setLoading("review");const response=await fetch("/api/v1/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:initial.project.id,artifactId:selected.id})});setLoading("");if(response.ok){setToast("已提交人工审核");await refresh();}}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setLoading("upload");const form=new FormData();form.set("file",file);const response=await fetch(`/api/v1/projects/${initial.project.id}/sources`,{method:"POST",body:form});const json=await response.json();setLoading("");event.target.value="";if(response.ok){setToast(`已解析 ${file.name}，提取 ${json.data.facts.length} 条事实候选`);await refresh();}else setToast(json.error?.message||"资料上传失败");}
  async function restore(versionId:string){if(!selected)return;setLoading(versionId);const response=await fetch(`/api/v1/projects/${initial.project.id}/artifacts/${selected.id}/versions/${versionId}/restore`,{method:"POST"});const json=await response.json();setLoading("");if(response.ok){setToast(`已恢复为新版本 v${json.data.version}`);await refresh();}else setToast(json.error?.message||"恢复版本失败");}
  const version=useMemo(()=>selected?.version||data.artifactVersions?.find((v:any)=>v.artifactId===selected?.id),[selected,data]);
  return <>{toast&&<div className="toast" onClick={()=>setToast("")}>{toast}</div>}<div className="snapshot-ribbon" style={{marginBottom:16}}>{["项目资料","事实快照",`v${snapshot?.version||1}`,"全部成果","人工审核"].map((label,index)=><div className="snapshot-node" key={`${label}-${index}`}><span className="snapshot-dot"/><div><strong>{label}</strong><small>{index===2?snapshot?.id?.slice(0,12):index<3?"已同步":"同一快照"}</small></div></div>)}</div><div className="project-tabs">{["总览","资料","事实卡","任务简报","提示词","方案","脚本","图片","视频","复核","智能体协作","导出"].map((tab,index)=><button key={tab} className={`project-tab ${index===0?"active":""}`}>{tab}</button>)}</div><div className="project-shell">
    <aside className="pane"><div className="card"><div className="card-head"><h3>项目资料</h3><Badge tone={statusTone(data.project.status)}>{statusLabel(data.project.status)}</Badge></div><div className="card-pad"><div className="fact-type">品牌 / 商品</div><div className="fact-value">{data.brand?.name} · {data.products?.[0]?.name}</div><div className="source-quote">{data.project.targetPlatforms.join(" / ")}<br/>{data.project.targetAudience}</div><label className="button secondary" style={{marginTop:12,width:"100%",cursor:"pointer"}}>{loading==="upload"?<LoaderCircle size={13}/>:<UploadCloud size={13}/>}上传并解析资料<input aria-label="上传项目资料" type="file" accept=".pdf,.docx,.pptx,.xlsx,.csv,.txt,.md,.jpg,.jpeg,.png" onChange={upload} style={{display:"none"}}/></label><div className="hint" style={{marginTop:7}}>白名单文件，单个不超过 20MB；上传后先形成事实候选。</div></div></div><div className="card"><div className="card-head"><h3>事实卡</h3><span className="small muted">{data.facts.length} 条</span></div><div className="card-pad stack" style={{paddingTop:12}}>{data.facts.map((fact:any)=><div className={`fact-card ${fact.status}`} key={fact.id}><div className="row between"><div className="fact-type">{fact.type}</div><Badge tone={fact.status==="missing"?"amber":fact.status==="conflicting"?"red":"jade"}>{statusLabel(fact.status)}</Badge></div><div className="fact-value">{fact.value||"等待补充"}</div>{fact.sourceQuote&&<div className="source-quote">“{fact.sourceQuote}”</div>}{["missing","inferred","conflicting"].includes(fact.status)&&<button className="button secondary" style={{minHeight:30,padding:"0 10px",marginTop:8}} onClick={()=>confirm(fact)} disabled={loading===fact.id}>{loading===fact.id?<LoaderCircle size={12}/>:<Check size={12}/>}确认</button>}</div>)}</div></div></aside>
    <section className="pane"><div className="card"><div className="card-head"><div><h2>{selected?.title||"项目尚无生成成果"}</h2><div className="list-meta">{selected?`${statusLabel(selected.status)} · 版本 v${selected.currentVersion}`:"点击下方按钮生成整套活动"}</div></div><div className="row"><button className="button secondary" onClick={bundle} disabled={loading==="bundle"}>{loading==="bundle"?<LoaderCircle size={14}/>:<Sparkles size={14}/>}生成整套活动</button>{selected&&<button className="button primary" onClick={review} disabled={loading==="review"}><ShieldCheck size={14}/>提交审核</button>}</div></div>{selected?<div className="editor">{version?.content||"选择成果查看内容"}</div>:<div className="editor" style={{display:"grid",placeItems:"center",textAlign:"center"}}><div><Sparkles size={36} color="var(--indigo)" style={{margin:"0 auto 14px"}}/><h2>从同一事实快照开始生产</h2><p className="subtitle">系统会生成方案、脚本、主图规划、图片提示词、视频分镜、Remotion 草稿、排期与质量报告。</p></div></div>}</div>{data.artifacts.length>0&&<div className="card"><div className="card-head"><h3>成果版本</h3><span className="small muted">人工内容不会被静默覆盖</span></div><div className="card-pad" style={{paddingTop:4,paddingBottom:4}}><ul className="list">{data.artifacts.map((artifact:any)=><li className="list-item" key={artifact.id} onClick={()=>setSelected(artifact)} style={{cursor:"pointer"}}><div className="list-icon"><FileText size={17}/></div><div className="list-copy"><div className="list-title">{artifact.title}</div><div className="list-meta">v{artifact.currentVersion} · 快照 {artifact.factSnapshotId.slice(0,12)}</div></div><Badge tone={statusTone(artifact.status)}>{statusLabel(artifact.status)}</Badge><ChevronRight size={14} color="var(--muted)"/></li>)}</ul></div></div>}</section>
    <aside className="pane"><div className="card card-pad"><div className="row between"><h3 style={{margin:0}}>质量与风险</h3><ShieldCheck size={17} color="var(--jade)"/></div><div style={{marginTop:16}}><div className="row between small"><span>来源覆盖</span><strong>92%</strong></div><div className="progress" style={{marginTop:7}}><span style={{width:"92%"}}/></div></div><div className="card" style={{padding:12,marginTop:14,background:"var(--amber-soft)",borderColor:"#f4d29f"}}><strong style={{fontSize:11}}>仍有必须确认项</strong><p className="hint" style={{margin:"6px 0 0"}}>{data.facts.filter((f:any)=>["missing","conflicting"].includes(f.status)).map((f:any)=>f.type).join("、")||"无"}</p></div></div><div className="card card-pad"><h3>当前事实快照</h3><div className="mono small">{snapshot?.id}</div><div className="source-quote">校验：{snapshot?.checksum?.slice(0,24)}…<br/>共 {snapshot?.facts?.length||0} 条事实</div></div>{selected&&<div className="card card-pad"><h3>历史版本</h3><div className="stack" style={{gap:8}}>{data.artifactVersions?.filter((item:any)=>item.artifactId===selected.id).map((item:any)=><div className="row between" key={item.id}><span className="small">v{item.version} · {item.changeSummary}</span><button className="button secondary" style={{minHeight:28,padding:"0 8px"}} disabled={item.version===selected.currentVersion||loading===item.id} onClick={()=>restore(item.id)}>{loading===item.id?<LoaderCircle size={11}/>:<RotateCcw size={11}/>}恢复</button></div>)}</div></div>}<div className="card card-pad"><h3>视频预览</h3><div style={{aspectRatio:"9/16",maxHeight:230,borderRadius:12,background:"linear-gradient(160deg,#242064,#6657e8)",display:"grid",placeItems:"center",color:"white",position:"relative",overflow:"hidden"}}><div style={{textAlign:"center"}}><Play size={28} style={{margin:"0 auto 9px"}}/><strong style={{fontSize:11}}>Remotion 模板预览</strong><div style={{fontSize:9,color:"#cbc8ff",marginTop:5}}>价格与规格由确定性图层渲染</div></div><div style={{position:"absolute",inset:"8% 6%",border:"1px dashed rgba(255,255,255,.35)",borderRadius:8}}/></div><a className="button secondary" href="/video-preview" style={{width:"100%",marginTop:10}}><RotateCcw size={13}/>打开视频工作室</a></div></aside>
  </div></>;
}
