"use client";
import { useState, type ChangeEvent } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, FileText, LoaderCircle, UploadCloud, X } from "lucide-react";
import { useRouter } from "next/navigation";

const steps = ["选择任务","品牌与商品","上传资料","设置目标","AI 预检查"];
const templates: Array<[string, string]> = [["新品上市","从资料到整套上市内容"],["大型促销","活动机制与内容矩阵"],["日常营销","持续内容与转化实验"],["直播活动","货盘、节奏与直播脚本"],["短视频投放","开场 A/B 与素材规划"],["商品详情页重做","卖点、证据与页面结构"],["品牌年度规划","目标、节奏与预算"],["渠道增长","流量、转化与复购"],["竞品研究","证据化竞品对比"]];

export function ProjectWizard() {
  const [step,setStep] = useState(0); const [type,setType] = useState("新品上市"); const [name,setName] = useState("我的新品测试项目"); const [brandName,setBrandName]=useState("");const [productName,setProductName]=useState("");const [platforms,setPlatforms] = useState(["小红书","抖音"]); const [objective,setObjective] = useState("根据我上传的资料生成一套有事实依据、可下载的电商内容"); const [budget,setBudget]=useState(0);const [campaignStart,setCampaignStart]=useState("");const [files,setFiles]=useState<File[]>([]);const [loading,setLoading] = useState(false);const [message,setMessage]=useState(""); const router=useRouter();
  function selectFiles(event:ChangeEvent<HTMLInputElement>){const next=Array.from(event.target.files||[]);event.target.value="";setFiles(current=>[...current,...next].filter((file,index,all)=>all.findIndex((item)=>item.name===file.name&&item.size===file.size)===index));}
  async function create(){setLoading(true);setMessage("正在创建空白项目…");const response=await fetch("/api/v1/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,type,brandName,productName,objective,businessGoal:objective,targetPlatforms:platforms,...(budget>0?{budget}:{}),...(campaignStart?{campaignStart}:{})})});const json=await response.json();if(!response.ok){setLoading(false);setMessage(json.error?.message||"项目创建失败");return;}const projectId=json.data.id as string;const failures:string[]=[];for(const [index,file] of files.entries()){setMessage(`正在解析资料 ${index+1}/${files.length}：${file.name}`);const form=new FormData();form.set("file",file);const upload=await fetch(`/api/v1/projects/${projectId}/sources`,{method:"POST",body:form});if(!upload.ok){const result=await upload.json();failures.push(`${file.name}：${result.error?.message||result.data?.source?.error||"解析失败"}`);}}setLoading(false);if(failures.length)sessionStorage.setItem("lai-project-notice",`部分资料需要重试：${failures.join("；")}`);router.push(`/projects/${projectId}`);}
  return <div className="wizard"><aside className="card wizard-steps">{steps.map((label,index)=><div className={`wizard-step ${step===index?"active":""}`} key={label}><span className="wizard-number">{index<step?<CheckCircle2 size={13}/>:index+1}</span><span>{label}</span></div>)}</aside><section className="card wizard-body">
    {step===0&&<><h2>这次要完成哪类任务？</h2><p className="subtitle">先选业务任务，系统会自动准备对应的事实项、提示词和工作室。</p><div className="choice-grid" style={{marginTop:22}}>{templates.map(([label,desc])=><button className={`choice ${type===label?"selected":""}`} onClick={()=>setType(label)} key={label}><strong>{label}</strong><small>{desc}</small></button>)}</div></>}
    {step===1&&<><h2>填写项目、品牌和商品</h2><p className="subtitle">不预置任何演示商品。品牌名和商品名可以先留空，上传后由资料识别并等待你确认。</p><div className="stack" style={{marginTop:22}}><div className="field"><label>项目名称</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="grid-2"><div className="field"><label>品牌名称（可留空）</label><input className="input" value={brandName} onChange={e=>setBrandName(e.target.value)} placeholder="从资料识别"/></div><div className="field"><label>商品名称（可留空）</label><input className="input" value={productName} onChange={e=>setProductName(e.target.value)} placeholder="从资料识别"/></div></div></div></>}
    {step===2&&<><h2>上传你自己的资料</h2><p className="subtitle">这个项目没有内置资料。选中的文件会真实上传、解析并提取事实候选。</p><label className="card" style={{marginTop:22,padding:38,textAlign:"center",borderStyle:"dashed",display:"block",cursor:"pointer"}}><UploadCloud size={30} style={{color:"var(--indigo)",margin:"0 auto 12px"}}/><strong style={{fontSize:13}}>选择 PDF、Office、表格、文本或图片（可多选）</strong><p className="hint" style={{margin:"8px 0 0"}}>单文件不超过 20MB；只检索本项目上传的资料</p><input aria-label="新项目资料" type="file" multiple accept=".pdf,.docx,.pptx,.xlsx,.csv,.txt,.md,.jpg,.jpeg,.png" onChange={selectFiles} style={{display:"none"}}/></label><div className="stack" style={{marginTop:14}}>{files.map((file)=><div className="list-item" key={`${file.name}-${file.size}`}><FileText size={18} color="var(--indigo)"/><div className="list-copy"><div className="list-title">{file.name}</div><div className="list-meta">等待创建后解析 · {Math.max(1,Math.round(file.size/1024))} KB</div></div><button className="icon-button" aria-label={`移除 ${file.name}`} onClick={()=>setFiles(current=>current.filter((item)=>item!==file))}><X size={14}/></button></div>)}</div>{files.length===0&&<div className="card card-pad" style={{marginTop:14,background:"var(--amber-soft)"}}>尚未选择资料。创建后仍可上传，但在上传前工作台不会调用 AI。</div>}</>}
    {step===3&&<><h2>设置目标</h2><p className="subtitle">只展示运营人员认识的字段，高级模型设置保持折叠。</p><div className="stack" style={{marginTop:22}}><div className="field"><label>业务目标</label><textarea className="textarea" value={objective} onChange={e=>setObjective(e.target.value)}/></div><div className="field"><label>目标平台</label><div className="row">{["小红书","抖音","淘宝","京东"].map(item=><button className={`choice ${platforms.includes(item)?"selected":""}`} style={{padding:"10px 14px"}} onClick={()=>setPlatforms(current=>current.includes(item)?current.filter(p=>p!==item):[...current,item])} key={item}><strong>{item}</strong></button>)}</div></div><div className="grid-2"><div className="field"><label>预算</label><input className="input" type="number" value={budget} onChange={(event)=>setBudget(Number(event.target.value)||0)}/></div><div className="field"><label>活动时间</label><input className="input" type="date" value={campaignStart} onChange={(event)=>setCampaignStart(event.target.value)}/></div></div></div></>}
    {step===4&&<><h2>AI 预检查</h2><p className="subtitle">创建后仍可修改；系统不会把推荐值当成已确认事实。</p><div className="grid-3" style={{marginTop:22}}><div className="card card-pad"><div className="metric-label">待解析资料</div><div className="metric-value" style={{color:"var(--jade)"}}>{files.length}</div><div className="metric-note">创建后逐份保存和解析</div></div><div className="card card-pad"><div className="metric-label">必须确认</div><div className="metric-value" style={{color:"var(--amber)"}}>1</div><div className="metric-note">活动价仍缺失</div></div><div className="card card-pad"><div className="metric-label">推荐技能</div><div className="metric-value">6</div><div className="metric-note">方案、脚本、视觉与复核</div></div></div><div className="card card-pad" style={{marginTop:16,background:"var(--amber-soft)"}}><strong style={{fontSize:12}}>创建后先核对自动提取结果</strong><p className="hint" style={{margin:"6px 0 0"}}>系统只提出事实候选；价格、日期、资质和功效仍要由你确认。</p></div></>}
    {message&&<div className="hint" role="status" style={{marginTop:18}}>{message}</div>}<div className="row between" style={{marginTop:30}}><button className="button secondary" disabled={step===0||loading} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={15}/>上一步</button>{step<4?<button className="button primary" onClick={()=>setStep(s=>s+1)}>下一步<ArrowRight size={15}/></button>:<button className="button jade" onClick={create} disabled={loading}>{loading?<LoaderCircle size={15}/>:<CheckCircle2 size={15}/>}创建、解析并进入项目</button>}</div>
  </section></div>;
}
