"use client";
import { useEffect, useState } from "react";
import { Check, Clipboard, Download, LoaderCircle, Play, Save, Send, Sparkles } from "lucide-react";

const tasks=["做新品上市方案","做营销活动方案","做年度运营规划","做竞品分析","写短视频脚本","写直播脚本","写商品文案","做商品主图","做活动海报","做详情页","做视频分镜","生成图片提示词","生成视频提示词","分析上传资料","修改已有内容","让另一个智能体继续工作","自定义任务"];
type Result={spec:any;variants:any[];explanation:any;evaluation:any};

export function PromptLab(){
  const [objective,setObjective]=useState("给青麦脆草莓燕麦杯做一套新品上市方案，先验证小红书和抖音的内容钩子");const [selectedTask,setSelectedTask]=useState<string>(tasks[0]!);const [result,setResult]=useState<Result|null>(null);const [tab,setTab]=useState(0);const [loading,setLoading]=useState("");const [toast,setToast]=useState("");
  useEffect(()=>{const params=new URLSearchParams(location.search);const obj=params.get("objective");if(obj)setObjective(obj);if(params.get("ready")==="1")void generate(obj||objective);},[]);
  async function generate(value=objective){setLoading("generate");const response=await fetch("/api/v1/prompts/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:"prj_qingmai_launch",objective:value})});const json=await response.json();setLoading("");if(response.ok){setResult(json.data);setToast("已生成三个版本，并完成逐项评分");}else setToast(json.error?.message||"生成失败");}
  async function run(){if(!result)return;setLoading("run");const response=await fetch("/api/v1/prompts/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:result.spec.projectId,promptSpecId:result.spec.id,artifactType:selectedTask.includes("脚本")?"script":"proposal"})});setLoading("");setToast(response.ok?"已使用 Mock Provider 生成成果草稿":"运行失败");}
  async function saveTemplate(){if(!result)return;setLoading("template");const response=await fetch("/api/v1/templates",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:result.spec.projectId,promptSpecId:result.spec.id})});const json=await response.json();setLoading("");setToast(response.ok?`已保存模板：${json.data.name}`:json.error?.message||"保存模板失败");}
  async function createHandoff(){if(!result)return;setLoading("handoff");const response=await fetch("/api/v1/handoffs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:result.spec.projectId,promptSpecId:result.spec.id,objective})});const json=await response.json();setLoading("");setToast(response.ok?`交接包已创建：${json.data.handoffId}`:json.error?.message||"创建交接包失败");}
  const current=result?.variants[tab];const missing=result?.explanation.missing||[];const score=result?.evaluation.total||0;
  return <>{toast&&<div className="toast" onClick={()=>setToast("")}>{toast}</div>}<div className="prompt-layout"><div className="stack">
    <section className="card card-pad"><div className="row between"><div><div className="eyebrow">Guided Builder</div><h2 style={{margin:"7px 0 5px"}}>先选业务任务，不从空白提示词开始</h2></div><span className="badge indigo">AI 新手模式</span></div><div className="task-cards" style={{marginTop:16}}>{tasks.map(task=><button key={task} className={`task-card ${selectedTask===task?"active":""}`} onClick={()=>{setSelectedTask(task);setObjective(task==="自定义任务"?"":`${task}：${objective.split("：").pop()}`)}}>{task}</button>)}</div></section>
    <section className="card card-pad"><div className="field"><label>用一句话说目标</label><textarea className="textarea" value={objective} onChange={event=>setObjective(event.target.value)} placeholder="例如：给这款燕麦杯写一个30秒短视频脚本"/></div><div className="grid-3" style={{marginTop:14}}><div className="field"><label>项目</label><select className="select"><option>青麦脆夏日上新</option></select></div><div className="field"><label>商品</label><select className="select"><option>青麦脆·草莓燕麦杯</option></select></div><div className="field"><label>平台</label><select className="select"><option>小红书 + 抖音</option></select></div></div><div className="card" style={{padding:12,marginTop:14,background:!result?"var(--surface-soft)":missing.length?"var(--amber-soft)":"var(--jade-soft)"}}><div className="row between"><strong style={{fontSize:11}}>{!result?"生成时会检查项目事实":missing.length?"一次性补充问题":"项目资料已能支撑生成"}</strong><span className="small">{!result?"待检查":`${missing.length} 项`}</span></div><p className="hint" style={{margin:"6px 0 0"}}>{!result?"系统会核对规格、配料、价格、活动时间和来源，再决定是否需要补充。":missing.join("；")||"规格、配料与活动时间已从项目自动补全。"}</p></div><div className="row between" style={{marginTop:16}}><details><summary className="small muted" style={{cursor:"pointer"}}>专业模式 · 查看高级结构</summary><pre className="mono small">PromptSpec / 变量 / 输出结构 / Provider 适配</pre></details><button className="button primary" onClick={()=>generate()} disabled={loading==="generate"}>{loading==="generate"?<LoaderCircle size={15}/>:<Sparkles size={15}/>}生成专业提示词</button></div></section>
    {result&&<section className="card"><div className="card-head"><div><h2>提示词结果</h2><div className="list-meta">同一事实快照 · {result.spec.factSnapshotId}</div></div><div className="row"><button className="button secondary" onClick={()=>{void navigator.clipboard.writeText(current.content);setToast("提示词已复制");}}><Clipboard size={14}/>复制</button><button className="button primary" onClick={run} disabled={loading==="run"}>{loading==="run"?<LoaderCircle size={14}/>:<Play size={14}/>}立即运行</button></div></div><div className="prompt-tabs">{result.variants.map((variant,index)=><button className={`prompt-tab ${tab===index?"active":""}`} onClick={()=>setTab(index)} key={variant.id}>{variant.title}</button>)}</div><div className="prompt-output">{current.content}</div><div className="row" style={{padding:"0 18px 18px",flexWrap:"wrap"}}><button className="button secondary" onClick={saveTemplate} disabled={loading==="template"}>{loading==="template"?<LoaderCircle size={13}/>:<Save size={13}/>}保存为模板</button><a className="button secondary" href={`/api/v1/prompts/${result.spec.id}/export?format=md`}><Download size={13}/>导出 Markdown</a><button className="button secondary" onClick={createHandoff} disabled={loading==="handoff"}>{loading==="handoff"?<LoaderCircle size={13}/>:<Send size={13}/>}交给其他智能体</button></div></section>}
  </div><aside className="stack">
    <section className="card card-pad"><div className="row between"><div><div className="eyebrow">Prompt Score</div><h2 style={{margin:"7px 0 0"}}>提示词体检</h2></div><div className="score-ring" style={{"--score":score} as React.CSSProperties}><strong>{score}</strong></div></div>{result?<div className="stack" style={{marginTop:18,gap:12}}>{result.evaluation.dimensions.map((item:any)=><div key={item.key}><div className="row between small"><span>{item.label}</span><strong>{item.score}</strong></div><div className="progress" style={{marginTop:6}}><span style={{width:`${item.score}%`,background:item.score<70?"var(--amber)":"var(--jade)"}}/></div><div className="hint" style={{marginTop:4}}>{item.suggestion}</div></div>)}</div>:<p className="subtitle" style={{marginTop:16}}>生成后会显示 11 个维度，不只给一个总分。</p>}</section>
    <section className="card card-pad"><h3>系统怎样理解这条提示词</h3>{result?<div className="stack" style={{gap:13}}><Explain title="要完成什么" items={[result.explanation.objective]}/><Explain title="使用哪些资料" items={result.explanation.sources}/><Explain title="已确认事实" items={result.explanation.confirmedFacts}/><Explain title="仍然缺少" items={result.explanation.missing}/><Explain title="风险" items={result.explanation.risks}/></div>:<p className="subtitle">这里会用电商运营语言解释资料、事实、缺失项和使用建议。</p>}</section>
  </aside></div></>;
}
function Explain({title,items}:{title:string;items:string[]}){return <div><div className="fact-type">{title}</div>{items.length?items.slice(0,4).map(item=><div className="row small" style={{alignItems:"flex-start",marginTop:6}} key={item}><Check size={12} color="var(--jade)" style={{marginTop:2,flex:"0 0 auto"}}/><span>{item}</span></div>):<div className="hint" style={{marginTop:5}}>暂无</div>}</div>}
