import fs from "node:fs/promises";
import { getCommerceService } from "@lai/shared";
import { newId, nowIso, type SourceDocument } from "@lai/domain";
import { providerRegistry } from "@lai/providers";
import { MockVirusScanner, normalizeUploadMimeType, safeWorkspacePath, validateUpload } from "@lai/security";
import { fail, ok, requireWorkbenchAccess } from "../../../../_lib/http";
import { resolveProjectUploadDirectory } from "../../../../_lib/source-storage";
export const runtime="nodejs";
export async function GET(request:Request,{params}:{params:Promise<{projectId:string}>}){try{requireWorkbenchAccess(request);const {projectId}=await params;return ok(getCommerceService().repo.listSources(projectId));}catch(error){return fail(error)}}
export async function POST(request:Request,{params}:{params:Promise<{projectId:string}>}){try{requireWorkbenchAccess(request);const {projectId}=await params;getCommerceService().getProject(projectId);const form=await request.formData();const file=form.get("file");if(!(file instanceof File))throw new Error("请选择要上传的文件");const mimeType=normalizeUploadMimeType({name:file.name,type:file.type});const safeName=validateUpload({name:file.name,type:mimeType,size:file.size});const bytes=new Uint8Array(await file.arrayBuffer());const scan=await new MockVirusScanner().scan(bytes);const dir=resolveProjectUploadDirectory("ws_demo",projectId);await fs.mkdir(dir,{recursive:true});const id=newId("src");const storagePath=safeWorkspacePath(dir,`${id}-${safeName}`);const createdAt=nowIso();if(!scan.clean){const source:SourceDocument={id,workspaceId:"ws_demo",projectId,fileName:safeName,mimeType,size:file.size,parser:"none",status:"quarantined",storagePath,createdAt,error:`病毒扫描未通过：${scan.threat}`};getCommerceService().saveSource(source);return ok(source,422)}await fs.writeFile(storagePath,bytes);const parsing:SourceDocument={id,workspaceId:"ws_demo",projectId,fileName:safeName,mimeType,size:file.size,parser:providerRegistry.document.name,status:"parsing",storagePath,createdAt};getCommerceService().saveSource(parsing);try{const parsed=await providerRegistry.document.parse({fileName:safeName,mimeType,bytes});const source:SourceDocument={...parsing,status:"parsed",extractedText:parsed.text,parsedAt:nowIso(),warnings:parsed.warnings};getCommerceService().saveSource(source);const facts=getCommerceService().extractFacts(projectId,id);return ok({source,facts,warnings:parsed.warnings},201);}catch(parseError){const source:SourceDocument={...parsing,status:"failed",error:parseError instanceof Error?parseError.message:"资料解析失败"};getCommerceService().saveSource(source);return ok({source,facts:[],warnings:[source.error]},422)}}catch(error){return fail(error)}}
