import fs from "node:fs/promises";
import path from "node:path";
import { getCommerceService } from "@lai/shared";
import { newId, nowIso, type SourceDocument } from "@lai/domain";
import { providerRegistry } from "@lai/providers";
import { MockVirusScanner, safeWorkspacePath, validateUpload } from "@lai/security";
import { fail, ok } from "../../../../_lib/http";
export const runtime="nodejs";
export async function GET(_:Request,{params}:{params:Promise<{projectId:string}>}){try{const {projectId}=await params;return ok(getCommerceService().repo.listSources(projectId));}catch(error){return fail(error)}}
export async function POST(request:Request,{params}:{params:Promise<{projectId:string}>}){try{const {projectId}=await params;getCommerceService().getProject(projectId);const form=await request.formData();const file=form.get("file");if(!(file instanceof File))throw new Error("请选择要上传的文件");const safeName=validateUpload({name:file.name,type:file.type,size:file.size});const bytes=new Uint8Array(await file.arrayBuffer());const scan=await new MockVirusScanner().scan(bytes);const root=path.resolve(process.env.INIT_CWD||process.cwd(),"data/uploads");const dir=safeWorkspacePath(root,"ws_demo",projectId);await fs.mkdir(dir,{recursive:true});const id=newId("src");const storagePath=safeWorkspacePath(dir,`${id}-${safeName}`);if(!scan.clean){const source:SourceDocument={id,workspaceId:"ws_demo",projectId,fileName:safeName,mimeType:file.type,size:file.size,parser:"none",status:"quarantined",storagePath,createdAt:nowIso(),error:`病毒扫描未通过：${scan.threat}`};getCommerceService().saveSource(source);return ok(source,422)}await fs.writeFile(storagePath,bytes);const parsed=await providerRegistry.document.parse({fileName:safeName,mimeType:file.type,bytes});const source:SourceDocument={id,workspaceId:"ws_demo",projectId,fileName:safeName,mimeType:file.type,size:file.size,parser:providerRegistry.document.name,status:"parsed",storagePath,extractedText:parsed.text,createdAt:nowIso(),parsedAt:nowIso(),error:parsed.warnings.join(" ")||undefined};getCommerceService().saveSource(source);const facts=getCommerceService().extractFacts(projectId,id);return ok({source,facts,warnings:parsed.warnings},201);}catch(error){return fail(error)}}
