"use client";
import { AbsoluteFill, cancelRender, continueRender, delayRender, Easing, Img, interpolate, Sequence, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import type { CommerceVideoProps } from "./types";

if (typeof document !== "undefined") {
  const handle = delayRender("正在加载内置中文字体");
  const face = new FontFace("Lai Noto Sans SC", `url(${staticFile("fonts/NotoSansSC-400.ttf")})`, { weight: "400" });
  face.load()
    .then((loaded) => { document.fonts.add(loaded); return document.fonts.ready; })
    .then(() => continueRender(handle))
    .catch((error) => cancelRender(error));
}

const SafeArea=()=> <div style={{position:"absolute",inset:"7% 6%",border:"2px dashed rgba(255,255,255,.22)",borderRadius:28,pointerEvents:"none"}}/>;
function BaseVideo({brandName,product,specification,price,cta,headline,subheadline,brandColor,accentColor,factSnapshotId,imageUri,mode}:{mode:"selling"|"ugc"|"promo"}&CommerceVideoProps){const frame=useCurrentFrame();const {fps,durationInFrames}=useVideoConfig();const enter=interpolate(frame,[0,fps*.7],[0,1],{extrapolateRight:"clamp",easing:Easing.out(Easing.cubic)});const progress=frame/durationInFrames;const zoom=interpolate(frame,[Math.floor(durationInFrames*.28),Math.floor(durationInFrames*.66)],[1.05,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <AbsoluteFill style={{background:`linear-gradient(155deg,${brandColor},#171540)`,color:"white",fontFamily:'"Lai Noto Sans SC","PingFang SC","Microsoft YaHei UI",sans-serif',overflow:"hidden"}}><div style={{position:"absolute",width:600,height:600,borderRadius:"50%",background:accentColor,opacity:.13,right:-240,top:-100}}/><Sequence from={0} durationInFrames={Math.floor(durationInFrames*.28)}><AbsoluteFill style={{padding:70,justifyContent:"center",transform:`translateY(${(1-enter)*50}px)`,opacity:enter}}><div style={{fontSize:24,letterSpacing:5,color:accentColor}}>{brandName} · {mode==="ugc"?"真实场景":"新品内容"}</div><div style={{fontSize:66,fontWeight:900,lineHeight:1.12,marginTop:24,whiteSpace:"pre-wrap"}}>{headline}</div><div style={{fontSize:28,lineHeight:1.55,color:"#d8d6ef",marginTop:22}}>{subheadline}</div></AbsoluteFill></Sequence><Sequence from={Math.floor(durationInFrames*.28)} durationInFrames={Math.floor(durationInFrames*.38)}><AbsoluteFill style={{padding:70,justifyContent:"center"}}><div style={{width:650,height:840,margin:"0 auto",borderRadius:50,background:"white",boxShadow:"0 30px 80px rgba(0,0,0,.3)",display:"grid",placeItems:"center",color:brandColor,textAlign:"center",padding:30,overflow:"hidden",transform:`scale(${zoom})`}}>{imageUri?<Img src={imageUri} style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:30}}/>:<div><div style={{fontSize:28,color:"#68657a"}}>{brandName}</div><div style={{fontSize:42,fontWeight:900,marginTop:18}}>{product}</div><div style={{marginTop:22,padding:"12px 18px",borderRadius:999,background:accentColor,fontSize:26}}>{specification}</div></div>}</div></AbsoluteFill></Sequence><Sequence from={Math.floor(durationInFrames*.66)}><AbsoluteFill style={{padding:70,justifyContent:"center"}}><div style={{fontSize:28,color:accentColor}}>{product}</div><div style={{fontSize:52,fontWeight:900,marginTop:20,lineHeight:1.3}}>{cta}</div><div style={{fontSize:26,marginTop:28,padding:"16px 22px",alignSelf:"flex-start",borderRadius:12,background:"white",color:brandColor}}>{price||`规格：${specification}`}</div><div style={{position:"absolute",bottom:84,left:70,fontSize:16,color:"#b9b7da"}}>事实快照 {factSnapshotId.slice(0,16)}</div></AbsoluteFill></Sequence><div style={{position:"absolute",left:0,bottom:0,height:8,width:`${progress*100}%`,background:accentColor}}/><SafeArea/></AbsoluteFill>}
export const SellingPoint15=(props:CommerceVideoProps)=><BaseVideo {...props} mode="selling"/>;
export const Ugc30=(props:CommerceVideoProps)=><BaseVideo {...props} mode="ugc"/>;
export const Promo30=(props:CommerceVideoProps)=><BaseVideo {...props} mode="promo"/>;

export const DEFAULT_VIDEO_PROPS:CommerceVideoProps={brandName:"待上传品牌",product:"待上传商品",specification:"规格待确认",headline:"把商品讲清楚",subheadline:"所有事实来自当前项目资料",cta:"先看清，再决定",brandColor:"#242064",accentColor:"#a9f0d2",factSnapshotId:"snap_preview"};
