"use client";
import { AbsoluteFill, Easing, interpolate, Sequence, useCurrentFrame, useVideoConfig } from "remotion";

export type CommerceVideoProps={product:string;specification:string;price?:string;cta:string;brandColor:string;accentColor:string;factSnapshotId:string};
const SafeArea=()=> <div style={{position:"absolute",inset:"7% 6%",border:"2px dashed rgba(255,255,255,.22)",borderRadius:28,pointerEvents:"none"}}/>;
function BaseVideo({product,specification,price,cta,brandColor,accentColor,factSnapshotId,mode}:{mode:"selling"|"ugc"|"promo"}&CommerceVideoProps){const frame=useCurrentFrame();const {fps,durationInFrames}=useVideoConfig();const enter=interpolate(frame,[0,fps*.7],[0,1],{extrapolateRight:"clamp",easing:Easing.out(Easing.cubic)});const progress=frame/durationInFrames;return <AbsoluteFill style={{background:`linear-gradient(155deg,${brandColor},#171540)`,color:"white",fontFamily:'"Microsoft YaHei UI",sans-serif',overflow:"hidden"}}><div style={{position:"absolute",width:600,height:600,borderRadius:"50%",background:accentColor,opacity:.13,right:-240,top:-100}}/><Sequence from={0} durationInFrames={Math.floor(durationInFrames*.28)}><AbsoluteFill style={{padding:70,justifyContent:"center",transform:`translateY(${(1-enter)*50}px)`,opacity:enter}}><div style={{fontSize:24,letterSpacing:5,color:accentColor}}>雾青谷 · {mode==="ugc"?"真实使用":"新品上新"}</div><div style={{fontSize:66,fontWeight:900,lineHeight:1.12,marginTop:24}}>忙碌早晨<br/>一杯带走</div></AbsoluteFill></Sequence><Sequence from={Math.floor(durationInFrames*.28)} durationInFrames={Math.floor(durationInFrames*.38)}><AbsoluteFill style={{padding:70,justifyContent:"center"}}><div style={{width:360,height:430,margin:"0 auto",borderRadius:50,background:"white",boxShadow:"0 30px 80px rgba(0,0,0,.3)",display:"grid",placeItems:"center",color:brandColor,textAlign:"center",padding:30}}><div><div style={{fontSize:28,color:"#68657a"}}>草莓燕麦杯</div><div style={{fontSize:42,fontWeight:900,marginTop:18}}>{product}</div><div style={{marginTop:22,padding:"12px 18px",borderRadius:999,background:accentColor,fontSize:26}}>{specification}</div></div></div></AbsoluteFill></Sequence><Sequence from={Math.floor(durationInFrames*.66)}><AbsoluteFill style={{padding:70,justifyContent:"center"}}><div style={{fontSize:28,color:accentColor}}>先看清配料，再决定</div><div style={{fontSize:52,fontWeight:900,marginTop:20}}>{cta}</div><div style={{fontSize:26,marginTop:28,padding:"16px 22px",alignSelf:"flex-start",borderRadius:12,background:"white",color:brandColor}}>{price||"活动价待人工确认"}</div><div style={{position:"absolute",bottom:84,left:70,fontSize:16,color:"#b9b7da"}}>事实快照 {factSnapshotId.slice(0,16)}</div></AbsoluteFill></Sequence><div style={{position:"absolute",left:0,bottom:0,height:8,width:`${progress*100}%`,background:accentColor}}/><SafeArea/></AbsoluteFill>}
export const SellingPoint15=(props:CommerceVideoProps)=><BaseVideo {...props} mode="selling"/>;
export const Ugc30=(props:CommerceVideoProps)=><BaseVideo {...props} mode="ugc"/>;
export const Promo30=(props:CommerceVideoProps)=><BaseVideo {...props} mode="promo"/>;

export const DEFAULT_VIDEO_PROPS:CommerceVideoProps={product:"青麦脆·草莓燕麦杯",specification:"45克×6杯",cta:"先看清，再决定",brandColor:"#242064",accentColor:"#a9f0d2",factSnapshotId:"snap_demo_current"};
